### PR TITLE
IOHook: Delect dead code

### PR DESCRIPTION
**Pull request by paulo-raca**
Previously, VirtualApp hooked into system calls to map files in their 'virtual data directories' to the folder where they were actually stored.

Instead, it now supplies the correct directories on the AppInfo -- Which is much simpler, and made a whole lot of native hooking to go unused.

As a bonus, all the arch-specific code went away and VirtualApp now supports all ABIs (Including arm64 and x86_64)

### CODE REVIEW

**Comment by cddjr** [comment]
还以为有黑科技可以做到不用io重定向...

**Comment by paulo-raca** [comment]
Sorry, what?
I don't understand Chinese, and Google translator wasn't very helpful...

**Comment by asLody** [comment]
IO Hook is an optional feature, it is not stable, so the code has not been used.

**Comment by paulo-raca** [comment]
Thanks.
I was under the impression it was dead code

**Comment by asLody** [comment]
If you're free I hope you can help us complete the VirtualApp's document :)

**Comment by paulo-raca** [comment]
Is there a document (where?), or do you mean in-code documentation?

Anyway, I can add some documentation while I read throgh it

**Pull request closed without merging**
